/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Alexa
 */
public class Attendants extends javax.swing.JInternalFrame {
    public Home homeScreen;
    public int attendantSelected = -1;
    
    /**
     * Creates new form Attendants
     */
    public Attendants(Home homeScreen) {
        initComponents();
        
        this.homeScreen = homeScreen;
    }

    public void selectAttendant(int index){
        this.attendantSelected = index;
        
        if(index == 1){
            this.attendant1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,0,0), 4, true));
            this.attendant2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(17, 19, 68), 1, true));
            this.labelSelected.setText("(Não sincronizado)");
            this.descriptionSelected.setText("Quando iniciar o atendimento pelo caixa 1, você verá que ele é um pouco fora de ordem.");
        }else{
            this.attendant2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,0,0), 4, true));
            this.attendant1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(17, 19, 68), 1, true));
            this.labelSelected.setText("(Sincronizado)");
            this.descriptionSelected.setText("Quando iniciar o atendimento pelo caixa 2, você verá que ele é feito da forma correta, por conta da aplicação de monitor.");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        attendant1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        attendant2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        startAttendance = new javax.swing.JButton();
        labelSelected = new javax.swing.JLabel();
        descriptionSelected = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 247, 245));
        setBorder(null);

        main.setBackground(new java.awt.Color(244, 247, 245));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 19, 68));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>\n<p><center>Escolha um dos caixas para o realizar o atendimento.</center></p>\n<p>Você irá observar que o atendimento realizado entre eles é diferente.</p>\n</html>");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        attendant1.setBackground(new java.awt.Color(244, 247, 245));
        attendant1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(17, 19, 68), 1, true));
        attendant1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attendant1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendant1MouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/attendant1.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(17, 19, 68));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html>\n<p><center><strong>Atendente 1</strong></center></p>\n<p>(Não possui sincronia no atendimento)</p>\n</html>");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout attendant1Layout = new javax.swing.GroupLayout(attendant1);
        attendant1.setLayout(attendant1Layout);
        attendant1Layout.setHorizontalGroup(
            attendant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attendant1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(attendant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(jLabel3)))
        );
        attendant1Layout.setVerticalGroup(
            attendant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendant1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        attendant2.setBackground(new java.awt.Color(244, 247, 245));
        attendant2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(17, 19, 68), 1, true));
        attendant2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attendant2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendant2MouseClicked(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/attendant2.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(17, 19, 68));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html>\n<p><center><strong>Atendente 2</strong></center></p>\n<p>(Possui sincronia no atendimento)</p>\n</html>");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout attendant2Layout = new javax.swing.GroupLayout(attendant2);
        attendant2.setLayout(attendant2Layout);
        attendant2Layout.setHorizontalGroup(
            attendant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attendant2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(attendant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(jLabel5)))
        );
        attendant2Layout.setVerticalGroup(
            attendant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendant2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5))
        );

        startAttendance.setBackground(new java.awt.Color(96, 113, 150));
        startAttendance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        startAttendance.setForeground(new java.awt.Color(244, 247, 245));
        startAttendance.setText("Iniciar Atendimento");
        startAttendance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startAttendanceMouseClicked(evt);
            }
        });

        labelSelected.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelSelected.setForeground(new java.awt.Color(17, 19, 68));
        labelSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        descriptionSelected.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        descriptionSelected.setForeground(new java.awt.Color(17, 19, 68));
        descriptionSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionSelected.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(startAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(labelSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(271, 271, 271))
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(attendant1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addComponent(attendant2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descriptionSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(attendant1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attendant2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(startAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(labelSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionSelected, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startAttendanceMouseClicked
        if(this.attendantSelected != -1)
            new Result(this).setVisible(true);
    }//GEN-LAST:event_startAttendanceMouseClicked

    private void attendant1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendant1MouseClicked
       this.selectAttendant(1);
    }//GEN-LAST:event_attendant1MouseClicked

    private void attendant2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendant2MouseClicked
        this.selectAttendant(2);
    }//GEN-LAST:event_attendant2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel attendant1;
    private javax.swing.JPanel attendant2;
    private javax.swing.JLabel descriptionSelected;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelSelected;
    private javax.swing.JPanel main;
    private javax.swing.JButton startAttendance;
    // End of variables declaration//GEN-END:variables
}
